"""add study guide section citation tables

Revision ID: 2a1f0a19dfca
Revises: c50959494cb5
Create Date: 2026-08-13 07:30:34.067125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a1f0a19dfca'
down_revision: Union[str, Sequence[str], None] = 'c50959494cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studyguide',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['analysissnapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studyguide_repo_id'), 'studyguide', ['repo_id'], unique=False)
    op.create_index(op.f('ix_studyguide_snapshot_id'), 'studyguide', ['snapshot_id'], unique=False)
    op.create_table('section',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('study_guide_id', sa.Uuid(), nullable=False),
    sa.Column('section_type', sa.Enum('overview', 'architecture', 'tradeoffs', 'glossary', 'deep_dive', name='sectiontype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('content_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diagram_mermaid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['study_guide_id'], ['studyguide.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_study_guide_id'), 'section', ['study_guide_id'], unique=False)
    op.create_table('citation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('claim_excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snippet_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_section_id'), 'citation', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citation_section_id'), table_name='citation')
    op.drop_table('citation')
    op.drop_index(op.f('ix_section_study_guide_id'), table_name='section')
    op.drop_table('section')
    op.drop_index(op.f('ix_studyguide_snapshot_id'), table_name='studyguide')
    op.drop_index(op.f('ix_studyguide_repo_id'), table_name='studyguide')
    op.drop_table('studyguide')
    # ### end Alembic commands ###
    # op.drop_table() doesn't drop the Postgres ENUM type it created (not owned
    # by any single table) — drop it explicitly or a re-upgrade fails with
    # "type already exists", same fix as the previous migration's downgrade().
    sa.Enum(name='sectiontype').drop(op.get_bind(), checkfirst=True)
