"""add quiz question attempt answersubmission tables

Revision ID: 3e61848b73c1
Revises: 38410b743b56
Create Date: 2026-08-13 16:44:08.200084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3e61848b73c1'
down_revision: Union[str, Sequence[str], None] = '38410b743b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('study_guide_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('generating', 'ready', 'failed', name='quizstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ),
    sa.ForeignKeyConstraint(['study_guide_id'], ['studyguide.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_repo_id'), 'quiz', ['repo_id'], unique=False)
    op.create_index(op.f('ix_quiz_study_guide_id'), 'quiz', ['study_guide_id'], unique=False)
    op.create_table('attempt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', name='attemptstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempt_quiz_id'), 'attempt', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_attempt_user_id'), 'attempt', ['user_id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('question_type', sa.Enum('mcq', 'fill_blank', name='questiontype'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=True),
    sa.Column('correct_index', sa.Integer(), nullable=True),
    sa.Column('fill_blank_mode', sa.Enum('code', 'concept', name='fillblankmode'), nullable=True),
    sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('acceptable_alternatives', sa.JSON(), nullable=True),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_quiz_id'), 'question', ['quiz_id'], unique=False)
    op.create_table('answersubmission',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('selected_index', sa.Integer(), nullable=True),
    sa.Column('answer_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answersubmission_attempt_id'), 'answersubmission', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_answersubmission_question_id'), 'answersubmission', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answersubmission_question_id'), table_name='answersubmission')
    op.drop_index(op.f('ix_answersubmission_attempt_id'), table_name='answersubmission')
    op.drop_table('answersubmission')
    op.drop_index(op.f('ix_question_quiz_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_attempt_user_id'), table_name='attempt')
    op.drop_index(op.f('ix_attempt_quiz_id'), table_name='attempt')
    op.drop_table('attempt')
    op.drop_index(op.f('ix_quiz_study_guide_id'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_repo_id'), table_name='quiz')
    op.drop_table('quiz')
    # ### end Alembic commands ###
    # op.drop_table() doesn't drop the Postgres ENUM types it created — same
    # gap as c50959494cb5's 'confidence' type, just four types this time.
    sa.Enum(name='fillblankmode').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='questiontype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='attemptstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='quizstatus').drop(op.get_bind(), checkfirst=True)
