"""add repo, analysis_snapshot, code_unit, user tables

Revision ID: a9fa75620a72
Revises: 23533d5e0ed5
Create Date: 2026-08-10 13:32:41.826389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9fa75620a72'
down_revision: Union[str, Sequence[str], None] = '23533d5e0ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('repo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.Enum('git_url', 'zip_upload', name='sourcetype'), nullable=False),
    sa.Column('source_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latest_snapshot_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_user_id'), 'repo', ['user_id'], unique=False)
    op.create_table('analysissnapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('commit_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'parsing', 'analyzing', 'generating', 'ready', 'failed', name='snapshotstatus'), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('language_summary', sa.JSON(), nullable=True),
    sa.Column('dependency_graph', sa.JSON(), nullable=True),
    sa.Column('entry_points', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysissnapshot_repo_id'), 'analysissnapshot', ['repo_id'], unique=False)
    # deferred: repo.latest_snapshot_id <-> analysissnapshot.repo_id is a circular FK
    # pair, so this constraint is added now that both tables exist (use_alter=True
    # on the model column keeps SQLAlchemy from trying to inline it into CREATE TABLE)
    op.create_foreign_key(
        'fk_repo_latest_snapshot_id', 'repo', 'analysissnapshot', ['latest_snapshot_id'], ['id']
    )
    op.create_table('codeunit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_type', sa.Enum('module', 'class', 'function', name='unittype'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('signature', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('docstring', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['analysissnapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codeunit_snapshot_id'), 'codeunit', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_codeunit_snapshot_id'), table_name='codeunit')
    op.drop_table('codeunit')
    op.drop_index(op.f('ix_analysissnapshot_repo_id'), table_name='analysissnapshot')
    op.drop_constraint('fk_repo_latest_snapshot_id', 'repo', type_='foreignkey')
    op.drop_table('analysissnapshot')
    op.drop_index(op.f('ix_repo_user_id'), table_name='repo')
    op.drop_table('repo')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
    # op.drop_table() doesn't drop the Postgres ENUM types it created (they're not
    # owned by any single table) — drop them explicitly or a re-upgrade fails with
    # "type already exists"
    sa.Enum(name='unittype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='snapshotstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='sourcetype').drop(op.get_bind(), checkfirst=True)
