"""add module_summary, pattern_claim, tradeoff_card

Revision ID: c50959494cb5
Revises: a9fa75620a72
Create Date: 2026-08-12 09:01:37.294735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c50959494cb5'
down_revision: Union[str, Sequence[str], None] = 'a9fa75620a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulesummary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_in_system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_concepts', sa.JSON(), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['analysissnapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modulesummary_snapshot_id'), 'modulesummary', ['snapshot_id'], unique=False)
    op.create_table('patternclaim',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('primary_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', name='confidence'), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('caveats', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['analysissnapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patternclaim_snapshot_id'), 'patternclaim', ['snapshot_id'], unique=False)
    op.create_table('tradeoffcard',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alternatives_considered', sa.JSON(), nullable=True),
    sa.Column('likely_reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tradeoff_cost', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', name='confidence'), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['analysissnapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tradeoffcard_snapshot_id'), 'tradeoffcard', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tradeoffcard_snapshot_id'), table_name='tradeoffcard')
    op.drop_table('tradeoffcard')
    op.drop_index(op.f('ix_patternclaim_snapshot_id'), table_name='patternclaim')
    op.drop_table('patternclaim')
    op.drop_index(op.f('ix_modulesummary_snapshot_id'), table_name='modulesummary')
    op.drop_table('modulesummary')
    # ### end Alembic commands ###
    # op.drop_table() doesn't drop the Postgres ENUM type it created (not owned
    # by any single table, and shared by both patternclaim and tradeoffcard) —
    # drop it explicitly or a re-upgrade fails with "type already exists".
    sa.Enum(name='confidence').drop(op.get_bind(), checkfirst=True)
